const eventNameConstantsMap = {
  PLAN_INVOICE_UPDATE: "PLAN_INVOICE_UPDATE",
  PLAN_SEAL_UPDATE: "PLAN_SEAL_UPDATE",
  PLAN_SNAPSHOT_UPDATE: "PLAN_SNAPSHOT_UPDATE",
  OUTBOUND_OPTIMIZATION_RESULT: "OUTBOUND_OPTIMIZATION_RESULT",
  OUTBOUND_OPTIMIZATION_REQUEST: "OUTBOUND_OPTIMIZATION_REQUEST",
  DELIVERY_ORDER_CREATE_RESPONSE: "DELIVERY_ORDER_CREATE_RESPONSE",
  OPTIMIZATION_RESPONSE: "OPTIMIZATION_RESPONSE",
  OPTIMIZED_PLANS:"OPTIMIZED_PLANS",
  TRANS_PLAN_UPDATES : "TRANS_PLAN_UPDATES",
  PLAN_TENDER_ASSIGNED_CARRIER_REQUEST: "PLAN_TENDER_ASSIGNED_CARRIER_REQUEST",
  SCH_PLAN_UPDATES: "SCH_PLAN_UPDATES",
  DELIVERY_ORDER_CREATE_REQUEST: "DELIVERY_ORDER_CREATE_REQUEST"
}

module.exports = eventNameConstantsMap

