import { Box, Paper } from "@mui/material"
import { DM_Serif_Display, Playfair_Display}  from "next/font/google"
import './globals.css';
import menubar from "./menubar";

const dmSerifDisplay =  DM_Serif_Display( {
    subsets: ['latin'], 
    weight: '400',
    variable: '--font-dm_serif',
})

const playfairDisplay =  Playfair_Display( {
  subsets: ['latin'], 
  weight: ['900'],
  variable: '--font-playfair_display',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
        
     

        </head>
        <body >
          <Paper elevation={10} >
            <Box 
            display="flex"
            sx={{height:100, justifyContent:'center' , alignItems:"center"}} > 
            <div  className={ `${dmSerifDisplay.variable} ${playfairDisplay.variable} `}>
              <div  className="dmSerif"> TGNews</div>
            </div>               
   
   
            </Box>
            <Box 
            display="flex"
            sx={{height:50, justifyContent:'center' , alignItems:"center"}} > 
               <menmenubar />
              <Box
              sx={{ border:1,  width: 200,  justifyContent:'center' , alignItems:"center"}}>
              <div  className={ `${dmSerifDisplay.variable} ${playfairDisplay.variable} `}>
                <div  className="playfairDisplay"> 
                  <div>TGNews</div>
                  
                </div>
              </div> 
              </Box>              

              <Box
              sx={{ border:1,  width: 200,  justifyContent:'center' , alignItems:"center"}}>
              <div  className={ `${dmSerifDisplay.variable} ${playfairDisplay.variable} `}>
                <div  className="playfairDisplay"> 
                  <div>TGNews</div>
                  
                </div>
              </div> 
              </Box> 
   
            </Box>
            <Box
              display="flex"
              sx={{   justifyContent:'center' , alignItems:"center"}}
            >
             <Box 
              
            
              sx={{ border:1, height:10000, width: 200,  justifyContent:'center' , alignItems:"center"}} > 
                

                   

              </Box>
              <Box 
              
            
              sx={{ border:1, height:10000, width: 800,  justifyContent:'center' , alignItems:"center"}} > 
                

                  <div  className={ `${dmSerifDisplay.variable} ${playfairDisplay.variable} `}> 
                    {children}
                  </div> 

              </Box>

              <Box 
              
            
              sx={{ border:1, height:10000, width: 200,  justifyContent:'center' , alignItems:"center"}} > 
                

                   

              </Box>
              
            </Box>
          </Paper >
        </body>
      
    </html>
  )
}
